services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  postgres:
    name: postgres
volumes:
  postgres:
    name: postgres